# Generated by Django 5.1.2 on 2024-11-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evento", "0002_alter_evento_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="evento",
            name="idCriador",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
