# Generated by Django 5.1.2 on 2024-11-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evento", "0003_alter_evento_descricao_alter_evento_idcriador"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="imagem",
            field=models.ImageField(
                default="imagens/default.jpg", null=True, upload_to="imagens/"
            ),
        ),
    ]
