# Generated by Django 5.1.2 on 2024-11-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evento", "0005_alter_evento_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="slug",
            field=models.SlugField(default="teste"),
        ),
    ]
