# Generated by Django 5.1.2 on 2024-11-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evento", "0006_evento_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
