# Generated by Django 5.1.2 on 2024-11-10 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evento", "0008_remove_evento_idcriador_evento_criador"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="criador",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
